import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
online_food_delivery_df = pd.read_csv("C:/Users/ss748/OneDrive/Documents/Desktop/onlinedeliverydata.csv")
online_food_delivery_df.head()
online_food_delivery_df.shape
print(online_food_delivery_df.info())
online_food_delivery_df.describe()
#Demographic of customers¶
#1) Distribution of consumer age
online_food_delivery_df['Age_group'] = pd.cut(online_food_delivery_df['Age'],bins = [15,20,25,30,35,40], labels = ['15-20y','20-25y','25-30y','30-35y','35-40y'])
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(15,5))

sns.distplot(online_food_delivery_df['Age'])
plt.title('Age group distribution')
sns.countplot(x='Age_group',data=online_food_delivery_df)
plt.show()
#2) Background of consumers¶
plt.figure(figsize=(20,10))
plt.subplot(2,3,1)
sns.countplot(data=online_food_delivery_df,x='Gender')
plt.title('Gender')
plt.xticks(rotation=60)
plt.subplot(2,3,2)
sns.countplot(data=online_food_delivery_df,x='Marital Status')
plt.title('Marital Status')
plt.xticks(rotation=60)
plt.subplot(2,3,3)
sns.countplot(data=online_food_delivery_df,x='Occupation')
plt.title('Occupation')
plt.xticks(rotation=60)
plt.subplot(2,3,4)
sns.countplot(data=online_food_delivery_df,x='Monthly Income')
plt.title('Monthly Income')
plt.xticks(rotation=60)
plt.subplot(2,3,5)
sns.countplot(data=online_food_delivery_df,x='Family size')
plt.title('Family size')
plt.xticks(rotation=60)
plt.subplot(2,3,6)
sns.countplot(data=online_food_delivery_df,x='Educational Qualifications')
plt.title('Educational Qualifications')
plt.tight_layout()
plt.show()
#Consumer preferences¶
#1) Medium of order
plt.figure(figsize=(15,5))
plt.subplot(1,2,1)
sns.countplot(data=online_food_delivery_df,x='Medium (P1)')
plt.subplot(1,2,2)
sns.countplot(data=online_food_delivery_df,x='Medium (P2)')
plt.xticks(rotation=60)
plt.tight_layout()
plt.show()
#2) Types of meal order
plt.figure(figsize=(10,5))
plt.subplot(1,3,1)
sns.countplot(data=online_food_delivery_df,x='Meal(P1)')
plt.xticks(rotation=60)
plt.tight_layout()
plt.show()
#3) Cuisine¶
plt.figure(figsize=(15,15))
plt.subplot(2,1,1)
sns.countplot(data=online_food_delivery_df,x='Perference(P1)')
plt.title('Perference(P1)',fontsize = 20)
plt.xlabel('Types',fontsize = 12)
plt.subplot(2,1,2)
sns.countplot(data=online_food_delivery_df,x='Perference(P2)')
plt.title('Perference(P2)',fontsize = 20)
plt.xlabel('Types',fontsize = 12)
plt.xticks(rotation=60)
plt.tight_layout()
plt.show()
#General purchase decision¶
#1) Features that influence users to use online food delivery
plt.figure(figsize=(20,10))
plt.subplot(2,4,1)
sns.countplot(data=online_food_delivery_df,x='Ease and convenient')
plt.title('Ease and convenient')
plt.xticks(rotation=60)
plt.subplot(2,4,2)
sns.countplot(data=online_food_delivery_df,x='Time saving')
plt.title('Time saving')
plt.xticks(rotation=60)
plt.subplot(2,4,3)
sns.countplot(data=online_food_delivery_df,x='More restaurant choices')
plt.title('More restaurant choices')
plt.xticks(rotation=60)
plt.subplot(2,4,4)
sns.countplot(data=online_food_delivery_df,x='Easy Payment option')
plt.title('Easy Payment option')
plt.title('Easy Payment option')
plt.xticks(rotation=60)
plt.subplot(2,4,5)
sns.countplot(data=online_food_delivery_df,x='More Offers and Discount')
plt.title('More Offers and Discount')
plt.xticks(rotation=60)
plt.subplot(2,4,6)
sns.countplot(data=online_food_delivery_df,x='Good Food quality')
plt.title('Good Food quality')
plt.xticks(rotation=60)
plt.subplot(2,4,7)
sns.countplot(data=online_food_delivery_df,x='Good Tracking system')
plt.title('Good Tracking system')
plt.xticks(rotation=60)
plt.tight_layout()
plt.show()
#2) Features that discourage users from using online food delivery¶
plt.figure(figsize=(20,10))
plt.subplot(2,4,1)
sns.countplot(data=online_food_delivery_df,x='Self Cooking')
plt.title('Self Cooking')
plt.xticks(rotation=60)
plt.subplot(2,4,2)
sns.countplot(data=online_food_delivery_df,x='Health Concern')
plt.title('Health Concern')
plt.xticks(rotation=60)
plt.subplot(2,4,3)
sns.countplot(data=online_food_delivery_df,x='Late Delivery')
plt.title('Late Delivery')
plt.xticks(rotation=60)
plt.subplot(2,4,4)
sns.countplot(data=online_food_delivery_df,x='Poor Hygiene')
plt.title('Poor Hygiene')
plt.xticks(rotation=60)
plt.subplot(2,4,5)
sns.countplot(data=online_food_delivery_df,x='Bad past experience')
plt.title('Bad past experience')
plt.xticks(rotation=60)
plt.subplot(2,4,6)
sns.countplot(data=online_food_delivery_df,x='Unavailability')
plt.title('Unavailability')
plt.xticks(rotation=60)
plt.subplot(2,4,7)
sns.countplot(data=online_food_delivery_df,x='Unaffordable')
plt.title('Unaffordable')
plt.xticks(rotation=60)
plt.tight_layout()
plt.show()
#4) Time of delivery influencing the purchase decision¶
plt.figure(figsize=(20,10))
plt.subplot(2,3,1)
sns.countplot(data=online_food_delivery_df,x='Influence of time')
plt.title('Influence of time')
plt.xticks(rotation=60)
plt.subplot(2,3,2)
sns.countplot(data=online_food_delivery_df,x='Maximum wait time')
plt.title('Maximum wait time')
plt.xticks(rotation=60)
plt.subplot(2,3,3)
sns.countplot(data=online_food_delivery_df,x='Less Delivery time')
plt.title('Less Delivery time')
plt.xticks(rotation=60)
plt.tight_layout()
plt.show()
#3) Reasons that cause the cancellation of online food delivery¶
plt.figure(figsize=(20,10))
plt.subplot(2,4,1)
sns.countplot(data=online_food_delivery_df,x='Long delivery time')
plt.title('Long delivery time')
plt.xticks(rotation=60)
plt.subplot(2,4,2)
sns.countplot(data=online_food_delivery_df,x='Delay of delivery person getting assigned')
plt.title('Delay of delivery person getting assigned')
plt.xticks(rotation=60)
plt.subplot(2,4,3)
sns.countplot(data=online_food_delivery_df,x='Delay of delivery person picking up food')
plt.title('Delay of delivery person picking up food')
plt.xticks(rotation=60)
plt.subplot(2,4,4)
sns.countplot(data=online_food_delivery_df,x='Wrong order delivered')
plt.title('Wrong order delivered')
plt.xticks(rotation=60)
plt.subplot(2,4,5)
sns.countplot(data=online_food_delivery_df,x='Missing item')
plt.title('Missing item')
plt.xticks(rotation=60)
plt.subplot(2,4,6)
sns.countplot(data=online_food_delivery_df,x='Order placed by mistake')
plt.title('Order placed by mistake')
plt.xticks(rotation=60)
plt.tight_layout()
plt.show()
#4) Time of delivery influencing the purchase decision¶
plt.figure(figsize=(20,10))
plt.subplot(2,3,1)
sns.countplot(data=online_food_delivery_df,x='Influence of time')
plt.title('Influence of time')
plt.xticks(rotation=60)
plt.subplot(2,3,2)
sns.countplot(data=online_food_delivery_df,x='Maximum wait time')
plt.title('Maximum wait time')
plt.xticks(rotation=60)
plt.subplot(2,3,3)
sns.countplot(data=online_food_delivery_df,x='Less Delivery time')
plt.title('Less Delivery time')
plt.xticks(rotation=60)
plt.tight_layout()
plt.show()

plt.figure(figsize=(20,10))
plt.subplot(1,3,1)
sns.countplot(data=online_food_delivery_df,x='Delivery person ability')
plt.title('Delivery person ability')
plt.xticks(rotation=60)
plt.subplot(1,3,2)
sns.countplot(data=online_food_delivery_df,x='Politeness')
plt.title('Politeness')
plt.xticks(rotation=60)
plt.subplot(1,3,3)
sns.countplot(data=online_food_delivery_df,x='Number of calls')
plt.title('Number of calls')
plt.xticks(rotation=60)
plt.tight_layout()
plt.show()
